name: CD-prd

on:
  push:
    tags:
      - 'release-*'

jobs:
  deploy-prd:
    if: github.event.base_ref == 'refs/heads/master'
    uses: onigomex/example-github-actions/.github/workflows/cd.yml@reusing-workflows
    with:
      env: prd
      environment: prd

