name: CD-prd

on:
  push:
    tags:
      - 'release-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prd
    if: github.event.base_ref == 'refs/heads/master'
    steps:
      - name: deploy prd
        run: echo "deploy prd"

