name: CD-prd

on:
  push:
    tags:
      - 'release-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prd
    if: github.ref_name == 'master'
    steps:
      - name: deploy prd
        run: echo "deploy prd"

