name: CD

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
        description: 'Environment (dev|stg|prd)'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    steps:
      - name: deploy ${{ inputs.env }}
        run: echo "deploy ${{ inputs.env }}"

